# Generated by Django 4.0.4 on 2022-06-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptInfo',
            fields=[
                ('用户id', models.IntegerField(
                    db_column='用户ID', primary_key=True, serialize=False)),
                ('领养日期', models.DateTimeField()),
                ('动物id', models.IntegerField(db_column='动物ID')),
                ('领养单编号', models.AutoField()),
                ('领养状态', models.CharField(max_length=50)),
                ('合照', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adopt_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('动物id', models.IntegerField(
                    db_column='动物ID', primary_key=True, serialize=False)),
                ('cd', models.CharField(max_length=10)),
                ('name', models.CharField(default='旺仔', max_length=10)),
                ('age', models.IntegerField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=11)),
                ('fur', models.CharField(max_length=11)),
                ('sex', models.CharField(max_length=11)),
                ('chara', models.CharField(blank=True, max_length=11, null=True)),
                ('addr', models.CharField(max_length=11)),
                ('is_adopt', models.CharField(max_length=11)),
                ('jveyu', models.CharField(blank=True, max_length=11, null=True)),
                ('vacc', models.CharField(blank=True, max_length=11, null=True)),
                ('ill', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'animal_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssistInfo',
            fields=[
                ('动物id', models.IntegerField(
                    db_column='动物ID', primary_key=True, serialize=False)),
                ('救助日期', models.DateTimeField()),
                ('救助单编号', models.AutoField()),
                ('用户名', models.IntegerField(db_column='用户名')),
                ('是否可被领养', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'assist_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('工号', models.IntegerField(primary_key=True, serialize=False)),
                ('性别', models.CharField(max_length=2)),
                ('电话', models.IntegerField()),
                ('密码', models.CharField(max_length=10)),
                ('在线时间', models.IntegerField()),
                ('年龄', models.IntegerField()),
                ('工龄', models.IntegerField()),
                ('投诉邮箱', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'manager_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=50, null=True)),
                ('phonum', models.CharField(max_length=13, null=True)),
                ('sex', models.CharField(default='男', max_length=2, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('photo', models.URLField(blank=True, max_length=256)),
                ('age', models.DateTimeField(blank=True, null=True)),
                ('crepoint', models.IntegerField(default='0')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
    ]
