# Generated by Django 4.0.4 on 2022-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptinfo',
            name='用户id',
            field=models.IntegerField(db_column='用户ID'),
        ),
        migrations.AlterField(
            model_name='animalinfo',
            name='age',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='assistinfo',
            name='用户名',
            field=models.CharField(db_column='用户名', default='admin', max_length=20),
        ),
    ]
