# Generated by Django 4.0.4 on 2022-06-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
    ]
