# Generated by Django 4.0.4 on 2022-06-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptinfo',
            name='用户id',
            field=models.IntegerField(db_column='用户ID'),
        ),
        migrations.AlterField(
            model_name='adoptinfo',
            name='领养单编号',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assistinfo',
            name='动物id',
            field=models.IntegerField(db_column='动物ID'),
        ),
        migrations.AlterField(
            model_name='assistinfo',
            name='救助单编号',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
