# Generated by Django 4.0.4 on 2022-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0002_alter_adoptinfo_用户id_alter_animalinfo_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptinfo',
            name='用户id',
        ),
        migrations.AddField(
            model_name='adoptinfo',
            name='用户名',
            field=models.CharField(db_column='用户名', default='admin', max_length=50),
        ),
    ]
