# Generated by Django 4.0.4 on 2022-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0002_alter_adoptinfo_用户id_alter_adoptinfo_领养单编号_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='动物id',
            field=models.AutoField(db_column='动物ID', primary_key=True, serialize=False),
        ),
    ]
