# Generated by Django 4.0.4 on 2022-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0003_remove_adoptinfo_用户id_adoptinfo_用户名'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitAdopt',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('ill', models.CharField(max_length=256)),
                ('loc', models.CharField(max_length=256)),
                ('pho', models.URLField(max_length=256)),
            ],
            options={
                'db_table': 'wait_adopt',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='animalinfo',
            name='can_adopt',
            field=models.IntegerField(default=0),
        ),
    ]
