# Generated by Django 4.0.4 on 2022-06-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acatdog', '0003_alter_animalinfo_动物id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinfo',
            name='is_adopt',
            field=models.CharField(default='否', max_length=11),
        ),
    ]
